### ISSUE TITLE
recursive file transfer does not work

### ISSUE THREAD

**Issue by gsikorski** [tylercrumpton/robotframework-scplibrary#3]
I get error:
`TypeError: tuple indices must be integers, not unicode`
when trying recursive Get File:

```
SCPLibrary.Get File  /var/log/  log/  recursive=True
```

Also, wildcard Get File does not work, e. g.:

```
SCPLibrary.Get File  /var/log/*  log/
```

returns error `No such file or directory: /var/log/*`

**Comment by tylercrumpton** [comment]
Thanks for reporting the issue! The `recursive=True` problem has been resolved in the v1.1.1 release (ce9257d) that is now available on pip, so give that a shot and let me know if you have any problems.

I'll open a separate issue on the wildcard problem, since the underlying SCP library claims support for wildcards, but it does not appear to function as intended.
